#9
sanyamaks/test_task_login_react pull request #10
Opened 2019-10-02 17:16 UTC by sanyamaks

Created component InputField

2019-10-02 18:39 UTC, akuznetsov-md commented on src/components/Button/Button.js
> +    if (this.props.className !== undefined && this.props.className !== null) {
Для удобного присваивания классов по условию есть npm пакет https://www.npmjs.com/package/classnames

2019-10-02 18:39 UTC, akuznetsov-md commented on src/components/InputField/InputField.css
> +  width: 488px;
Фиксированная ширина ни к чему. Пусть тянется на всю доступную ширину — это даст гораздо больше возможностей в настройке адаптивности

2019-10-02 18:39 UTC, akuznetsov-md commented on src/components/InputField/InputField.css
> +  letter-spacing: normal;
```
font-style: normal;
  font-stretch: normal;
  line-height: normal;
  letter-spacing: normal;
```

Эти правила никак не виляют на страницу. Не нужно их добавлять

2019-10-02 18:39 UTC, akuznetsov-md commented on src/components/InputField/InputField.js
> +        pattern={isNaN(this.props.pattern) ? this.props.pattern : ""}
`isNaN` — переводится как is not a number. NaN это результат некорректных манипуляций с числами:
```
console.log(0 / "hello"); // NaN
```

Т.е. здесь использование некорректное

2019-10-02 18:39 UTC, akuznetsov-md commented on src/components/InputField/InputField.js
> +        pattern={isNaN(this.props.pattern) ? this.props.pattern : ""}
Да и как мы выяснили pattern плохо работает в реакте, так что от него можно отказаться

2019-10-02 18:39 UTC, akuznetsov-md commented on src/components/InputField/InputField.js
> +        }
К чему такие проверки свойства required и autoFocus? Они разве предотвращают какую-то ошибку?

А вообще в реакте есть удобный механизм props spread. Весь твой код можно записать гораздо короче:
```
<input
  className={
    this.props.className !== undefined && this.props.className !== null
      ? className + " " + this.props.className
      : className
  }
  {...this.props}
/>
```

2019-10-02 18:51 UTC, sanyamaks commented on src/components/InputField/InputField.js
> +        pattern={isNaN(this.props.pattern) ? this.props.pattern : ""}
Я уже заметил, что ошибся, поэтому выше видно, что Button поменял.
А здесь, видимо, забыл исправить.

2019-10-02 18:56 UTC, sanyamaks commented on src/components/InputField/InputField.js
> +        }
Когда передавал className компоненту-ребенку, в названии появлялось undefined в случае не передачи className.
Поэтому делал проверку. 
Здесь, дабы не допустить подобного, сделал также. Хотя в голове остался вопрос, насколько это необходимо?

2019-10-02 19:04 UTC, akuznetsov-md commented on src/components/InputField/InputField.js
> +        }
В названии появлялся undefined потому что ты приводил undefined к строке в случае конкатенации.

2019-10-07 17:09 UTC, sanyamaks commented
Справился с проблемой `TypeError: NetworkError when attempting to fetch resource` заменив `input` на `button` в форме.
Характера проблемы так и не понял.
Проблема появилась после того, как убрал `pattern` из `input email`

2019-10-11 08:47 UTC, akuznetsov-md requested changes

2019-10-11 08:47 UTC, akuznetsov-md commented on src/components/Button/Button.js
> +        })}
Достаточно написать:
```
classNames("button", this.props.className)
```

2019-10-11 08:47 UTC, akuznetsov-md commented on src/components/InputField/InputField.js
> +        })}
Аналогично Button — можно упростить

2019-10-11 08:47 UTC, akuznetsov-md commented on src/components/Login/Login.js
> +          })}
В реальном проекте компоненты используются больше чем на одном экране. С таким подходом тебе придется копировать стили невалидного поля ввода для каждой формы. Чтобы этого не делать, эти стили нужно деражать внутри компонента: "невалидный" это одного из состояний поля ввода, за отображение которого должен отвечать сам компонент. Стили всех логических состояний компонента должны быть описаны внутри самого компонента. Извне мы задаем позициорнирование и отступы;

2019-10-11 08:47 UTC, akuznetsov-md commented on src/components/Login/Login.js
> +          })}
Каждому конкретному инпуту мы просто указываем свойство invalid или error, в зависимости от которого внутри назначается соответствующий класс. Либо мы задаем правила валидации через свойства компонента, и в зависимости от того, проходит ли значение указанные правила меняем его состояние.

2019-10-11 10:28 UTC, sanyamaks commented on src/components/Button/Button.js
> +        })}
Очень удобно.
То есть я правильно понимаю, что в модуле уже вложены проверки на наличие переданных данных ?

2019-10-11 10:38 UTC, akuznetsov-md commented on src/components/Button/Button.js
> +        })}
Да, там это уже есть

2019-10-11 11:15 UTC, sanyamaks commented on src/components/Login/Login.js
> +          })}
->Либо мы задаем правила валидации через свойства компонента, и в зависимости от того, проходит ли значение указанные правила меняем его состояние.
Со стилями внутри компонента понял, но мог бы ты объяснить указанную фразу?

2019-10-11 13:47 UTC, akuznetsov-md commented on src/components/Login/Login.js
> +          })}
Да, конечно. Можно в компонент передавать не просто булевый флаг invaliad=true/false, а правила валидации. Правила валидации могут состоять из нескольких свойств: required, maxLength, minLength и т.п. А уже внутри компонента в обработчике onChange проверять значение на соответствие этим правилам и выставлять состояние invalid через state.

Но я бы не стал сейчас сильно париться с правилами валидации и указывал бы просто флаг. орошая валидация форм это сложно

2019-10-11 23:04 UTC, sanyamaks commented
![изображение](https://user-images.githubusercontent.com/47739310/66689523-5ebcde00-ec9c-11e9-9bcb-6c8f92b90f46.png)
При передаче `invalid` показывает вот такую ошибку. не совсем понимаю, что не так. Необходимо ведь передать булевое значение.
Нашел решение - использовать вместо true и false 1 и 0. С практической точки зрения это было бы вполне реализуемо. Есть ли минусы у такого использования в сравнении с true и false?

2019-10-13 19:56 UTC, sanyamaks commented
Хотел сделать отдельную ветку `9.1` не получилось. 
Заменил true и false на 1 и 0 для исправления ошибки.
Основные замечания исправил в коммите на 1 выше.

2019-10-14 17:09 UTC, akuznetsov-md commented
`invalid` —  нестандартный атрибут для инпутов, поэтому возникает такой ворнинг.

Чтобы это исправить, нужно убрать этот атрибут из числа тех, что прокидывается в стандартный `input`:

```
// otherProps в данном случае это копия this.props, но без свойств invalid и className
const { invalid, className, ...otherProps } = this.props;

<input
  {...otherProps}
  className={classNames("input-field", className, {
    "input-field_error": invalid
  })}
/>
```

2019-10-14 19:47 UTC, sanyamaks commented
```
const { invalid, className, ...otherProps } = this.props;
```
Я правильно понимаю, что этот кусок является тем, что называется деструктуризацией в js?

2019-10-15 06:07 UTC, akuznetsov-md commented
>Я правильно понимаю, что этот кусок является тем, что называется деструктуризацией в js?

Да

2019-10-28 20:13 UTC, closed without merging